name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get project
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish DBot.csproj -r linux-x64 -p:PublishSingleFile=true --self-contained false -c Release -o ./dist
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact-dbot
          path: ./dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@master
        with:
          name: artifact-dbot
          path: ./dist
          
      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
         REMOTE_USER: ${{ secrets.REMOTE_USER }}
         SOURCE: "dist"
         TARGET: ~/"
