name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish DBot.csproj -r linux-x64 -p:PublishSingleFile=true --self-contained false -c Release -o .dist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: dBot
        path: .dist/**
        if-no-files-found: error
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: dBot
          path: .dist/**
      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
         REMOTE_USER: ${{ secrets.REMOTE_USER }}
         SOURCE: "dist"
         TARGET: "~/"
